/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_signup;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import tugasRegistrasi.connectdb;

/**
 *
 * @author User
 */
public class signupsite extends javax.swing.JFrame {

    /**
     * Creates new form signupsite
     */
     Connection con=null;
    Statement st=null;
    public signupsite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telpon = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        konfirmasi = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_signup/sign_up_frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 140, 40));

        nama.setText("jTextField1");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 240, 30));

        email.setText("jTextField1");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 240, 30));

        telpon.setText("jTextField1");
        getContentPane().add(telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 230, 20));

        alamat.setText("jTextField1");
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 230, -1));

        password.setText("jPasswordField1");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 230, 30));

        konfirmasi.setText("konfirmasi");
        getContentPane().add(konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 220, 30));

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      PreparedStatement statement;
    
        String name=nama.getText();
       String Password=String.valueOf(password.getPassword());
       String Email=email.getText();
       String telepon=telpon.getText();
       String konfir=String.valueOf(konfirmasi.getPassword());
       String querysql="INSERT INTO tb_pelanggan (nama,email,password, telp) VALUES(?,?,?,?)";
       try{
           statement = connectdb.getConnection().prepareStatement(querysql);
           statement.setString(1, name);
           statement.setString(2,Email);
           statement.setString(3, Password);
           statement.setString(4, telepon);
           statement.executeUpdate();
           JOptionPane.showMessageDialog(this, "data berhasil ditambahkan","berhasil", JOptionPane.INFORMATION_MESSAGE);
           if(name.isEmpty()||Email.isEmpty()||Password.isEmpty()||telepon.isEmpty()){
               JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong", "error", JOptionPane.ERROR_MESSAGE);
           }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupsite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField konfirmasi;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField telpon;
    // End of variables declaration//GEN-END:variables
}
