/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khususadmin;
//package khusus admin adalah untuk menampung class-class yang berhubungan dengan kerja admin
import database.dbconnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public final class acceptretur extends javax.swing.JFrame {
//class acceptretur merupakan class yang berfungsi untuk menerima keputusan dari admin
//keputusan tersebut berupa retur dari pembeli, apakah admin setuju atau tidak
    /**
     * Creates new form acceptretur
     */
     public void tampilan_retur(){//objek untuk menampilkan tabel
        PreparedStatement statement;
        ResultSet result;
        DefaultTableModel model=new DefaultTableModel();//membuat tabel
        //nama-nama dari masing-masing kolom yang akan ditampilkan
        model.addColumn("no.");
        model.addColumn("nama_pelanggan");
        model.addColumn("nama_barang");
        model.addColumn("jumlah_barang");
        model.addColumn("jenis_kerusakan");
        model.addColumn("status");
        try{
    
            String sql="Select *From retur";//untuk menampilkan data-data ke tabel itu berasal dari data-data pada tabel retur di database
            //dnegan menggunakan query select all
            statement = dbconnection.getConnection().prepareStatement(sql);//menghubungkan ke database menggunakan class di package database
            result=statement.executeQuery();//mengexecute query, jika select menggunakan execute query, kalau update, delete, insert menggunakan exequteUpdate
            while(result.next()){
                //memasukkan data-data dari masing-masing kolom di database ke tabel model(nama tabel yang dibuat oada program)
               model.addRow(new Object[]{result.getString(1),result.getString(2), result.getString(3),result.getString(4),result.getString(5),result.getString(6)}); 
               data.setModel(model);
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());//menampilkan pesan jika error
        }
    }
    public void setuju(){//onjek untuk mengupdate data pada status, jika admin setuju
       PreparedStatement statement;
          ResultSet result;
          String nama=id.getText();
            String rusak="setuju";
      
          String querysql="update retur set status=? where id_retur=?";//query update
       try{
            statement = dbconnection.getConnection().prepareStatement(querysql);
            statement.setString(1, rusak);//string yang akan dimasukkan pada tanda '?' sesuaikan
            statement.setString(2, nama);
           
            if(!nama.isEmpty()){
            statement.executeUpdate();//execute query
            //sintaks untuk melakukan refresh langsung pada tabel setelah update
            DefaultTableModel model=(DefaultTableModel)data.getModel();
               model.setRowCount(0);
               tampilan_retur();
            JOptionPane.showMessageDialog(this, "retur disetujui","berhasil", JOptionPane.INFORMATION_MESSAGE);
            
            }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
    }
    //merupakan objek atau method untuk update keputusan admin jika tidak setuju//
    
    //cara kerjanya sama dnegan method setuju() hanya saja set string rusak='tidak setuju' jadi value yang akan dimasukkan ke database berbeda
     public void tidak_setuju(){
       PreparedStatement statement;
          ResultSet result;
          String nama=id.getText();
            String rusak="tidak setuju";
      
          String querysql="update retur set status=? where id_retur=?";
       try{
            statement = dbconnection.getConnection().prepareStatement(querysql);
            statement.setString(1, rusak);
            statement.setString(2, nama);
           
            if(!nama.isEmpty()){
            statement.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)data.getModel();
               model.setRowCount(0);
             
            JOptionPane.showMessageDialog(this, "retur tidak disetujui","berhasil", JOptionPane.INFORMATION_MESSAGE);
            
            }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
    }
    public acceptretur() {
        initComponents();
          tampilan_retur();//memanggil method tampilan di main agar ketika di run program akan otomatis kebuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        jenisrusak = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 590, 180));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 150, 30));
        getContentPane().add(jenisrusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 270, 260, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, 50));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/nexttombol.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/accept.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(602, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        //mouse klik ini berfungsi untuk dapat memilih tabel langsung dan meng-set nya ke textfield
        //jadi user dapat klik pada tabel langsung maka dapat melakukan insert, dsb
         DefaultTableModel model=(DefaultTableModel)data.getModel();//masnggil tabel
        String idbarang=(String) model.getValueAt(data.getSelectedRow(), 0);//akan diambil datanya pada kolom ke-0 atau pertama
        String rusak=(String) model.getValueAt(data.getSelectedRow(), 4);//data yang diambil pada selected row di kolom 4
        id.setText(idbarang);//set hasilnya ke text filed
        jenisrusak.setText(rusak);
        
    }//GEN-LAST:event_dataMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //manggil method sesuai dengan klik admin
        tidak_setuju();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setuju();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        //konfirmasi dialog untuk menanyakan kepada user
         int jawab= JOptionPane.showConfirmDialog(this, "klik yes untuk ke menu accept, no untuk keluar, dan cancel untuk batal");
        switch(jawab){
            case JOptionPane.YES_OPTION://jika memilih yes maka akan ke updel barang
                JOptionPane.showMessageDialog(this, "anda memilih ke menu acceptretur");
                new updelbarang().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION://kalo no bakal keluar dari program
                 JOptionPane.showMessageDialog(this, "anda memilih keluar");
                System.exit(0);
                  break;
            case JOptionPane.CANCEL_OPTION://kalo cancel tetap di halaman
                JOptionPane.showMessageDialog(this, "anda memilih cancel");
                break;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceptretur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceptretur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceptretur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceptretur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceptretur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenisrusak;
    // End of variables declaration//GEN-END:variables
}
