/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_signup;

import database.dbconnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import tugasRegistrasi.connectdb;
import tugasRegistrasi.home;

/**
 *
 * @author User
 */
public class loginsite extends javax.swing.JFrame {
String name,password;
    /**
     * Creates new form loginsite
     */
    public loginsite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordlogin = new javax.swing.JPasswordField();
        namalogin = new javax.swing.JTextField();
        view = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordlogin.setBackground(new java.awt.Color(102, 102, 255));
        passwordlogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordlogin.setBorder(null);
        passwordlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordlogin.setOpaque(false);
        passwordlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordloginMouseExited(evt);
            }
        });
        getContentPane().add(passwordlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 180, 30));

        namalogin.setBackground(new java.awt.Color(102, 102, 255));
        namalogin.setForeground(new java.awt.Color(255, 255, 255));
        namalogin.setBorder(null);
        namalogin.setOpaque(false);
        namalogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                namaloginMouseExited(evt);
            }
        });
        getContentPane().add(namalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 180, 30));

        view.setText("view");
        view.setBorder(null);
        view.setOpaque(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 50, 20));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 50, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_signup/loginbaru.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        setSize(new java.awt.Dimension(316, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         PreparedStatement statement;
       ResultSet result;
        String name=namalogin.getText();
       String password=String.valueOf(passwordlogin.getPassword());
       String querysql="SELECT*FROM pelanggan WHERE nama_pelanggan=? AND password=?";
       try{
           statement = dbconnection.getConnection().prepareStatement(querysql);
           statement.setString(1, name);
           statement.setString(2, password);
           result=statement.executeQuery();
           if(result.next()){
               menu hm=new menu();
               hm.setVisible(true);
               hm.pack();
               hm.setLocationRelativeTo(null);
               this.dispose();
           }else if(name.isEmpty()||password.isEmpty()){
               JOptionPane.showMessageDialog(this, "nama/password tidak boleh kosong", "error", JOptionPane.ERROR_MESSAGE);
           }
           else{
               JOptionPane.showMessageDialog(null,"nama/password tidak cocok", "error",2);
           }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void namaloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaloginMouseEntered
      
    }//GEN-LAST:event_namaloginMouseEntered

    private void namaloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaloginMouseClicked

    }//GEN-LAST:event_namaloginMouseClicked

    private void passwordloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordloginMouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_passwordloginMouseEntered

    private void passwordloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordloginMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_passwordloginMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        if(view.isSelected()){
            passwordlogin.setEchoChar((char)0);
        }else{
            passwordlogin.setEchoChar('*');
        }
    }//GEN-LAST:event_viewActionPerformed

    private void namaloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaloginMouseExited
  
    }//GEN-LAST:event_namaloginMouseExited

    private void passwordloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordloginMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordloginMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       new signupsite().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginsite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namalogin;
    private javax.swing.JPasswordField passwordlogin;
    private javax.swing.JCheckBox view;
    // End of variables declaration//GEN-END:variables
}
