/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_signup;

import database.dbconnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import khususadmin.acceptretur;
import khususadmin.updelbarang;

/**
 *
 * @author User
 */
public class loginadmin extends javax.swing.JFrame {

    /**
     * Creates new form loginadmin
     */
    //merupakan objek untuk mencari nama-nama maupun password yang dimiliki admin, dengan query select
    public void find_admin(){
        PreparedStatement statement;
       ResultSet result;
        String name=nama1.getText();//mendapatkan nilai dari gettext
       String password1=String.valueOf(password.getPassword());//mendapatkan nilai password dari field password
       String querysql="SELECT*FROM admin WHERE nama=? AND password=?";//query untuk menyocokkan apakah nama maupun password yang diinputkan admin benar2 ada pada database
       try{
           //untuk mengexecute query dan menyambungkannya dengan class bdconnection yang ada pada packace database
           statement = dbconnection.getConnection().prepareStatement(querysql);
           //set string yng dieksekusi untuk mengisi tanda '?' pada query, disesuaikan kalo 1, berarrti mengarah pada '?' pertama
           statement.setString(1, name);
           statement.setString(2, password1);
           result=statement.executeQuery();//execute query
           if(result.next()){
                int jawab= JOptionPane.showConfirmDialog(this, "klik yes untuk ke menu update, no untuk accept retur, dan cancel untuk batal");//jika query berhasil diexecute dan
               //nama-password admin memang ada maka akan muncul konfirmasi dialog apakah admin mau kemenu mana
        switch(jawab){//akan ada 3 kondisi dimana menggunakan switch
            case JOptionPane.YES_OPTION://jika user milih yes berarti akan diarahkan pada class updelbarang
                JOptionPane.showMessageDialog(this, "anda memilih update");
                updelbarang hm=new updelbarang();
               hm.setVisible(true);
               hm.pack();
               hm.setLocationRelativeTo(null);
               this.dispose(); 
                break;
            case JOptionPane.NO_OPTION://jika admin memilih no maka akan diarahkan ke enu acceptretur
                 JOptionPane.showMessageDialog(this, "anda memilih accept");
                  acceptretur ac=new acceptretur();
               ac.setVisible(true);
               ac.pack();
               ac.setLocationRelativeTo(null);
               this.dispose();
                  break;
            case JOptionPane.CANCEL_OPTION://jika admin memilih cancel maka admin akan tetap berada dihalaman
                JOptionPane.showMessageDialog(this, "anda memilih cancel");
                break;
        }
               
           }else if(name.isEmpty()||password1.isEmpty()){//kondisi jika semisal admin tidak mengisi field nama/passwrod maka 2 2 nya muncul pesan error
               JOptionPane.showMessageDialog(this, "nama/password tidak boleh kosong", "error", JOptionPane.ERROR_MESSAGE);
           }
           else{
               JOptionPane.showMessageDialog(null,"nama/password tidak cocok", "error",2);
           }
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
       
    }
    public loginadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 30));

        nama1.setBorder(null);
        nama1.setOpaque(false);
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        password.setBorder(null);
        password.setOpaque(false);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 30));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/login_frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
     find_admin();//jika admin menekan tombol login maka akan memanggil method find_admin() yang ada di atas
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login;
    private javax.swing.JTextField nama1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
