/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_signup;

import database.dbconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import tugasRegistrasi.connectdb;

/**
 *
 * @author User
 */
public class signupsite extends javax.swing.JFrame {

    /**
     * Creates new form signupsite
     */
     Connection con=null;
    Statement st=null;
    public signupsite() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telpon = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        konfirmasi = new javax.swing.JPasswordField();
        view2 = new javax.swing.JCheckBox();
        view1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 140, 30));

        nama.setBorder(null);
        nama.setOpaque(false);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 210, 20));

        email.setBorder(null);
        email.setOpaque(false);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 210, 20));

        telpon.setBorder(null);
        telpon.setOpaque(false);
        getContentPane().add(telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 210, 20));

        alamat.setBorder(null);
        alamat.setOpaque(false);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 210, 20));

        password.setBorder(null);
        password.setOpaque(false);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 200, -1));

        konfirmasi.setBorder(null);
        konfirmasi.setOpaque(false);
        konfirmasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                konfirmasiKeyReleased(evt);
            }
        });
        getContentPane().add(konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 210, 20));

        view2.setText("view");
        view2.setBorder(null);
        view2.setOpaque(false);
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        getContentPane().add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, 20));

        view1.setText("view");
        view1.setBorder(null);
        view1.setOpaque(false);
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        getContentPane().add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_signup/sign_up_frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      PreparedStatement statement;
    
        String name=nama.getText();
       String Password=String.valueOf(password.getPassword());
       String Email=email.getText();
       String telepon=telpon.getText();
       String tempattinggal=alamat.getText();
       String konfir=String.valueOf(konfirmasi.getPassword());
       String querysql="INSERT INTO pelanggan (nama_pelanggan,password, telp,email,alamat) VALUES(?,?,?,?,?)";
       try{
           statement = dbconnection.getConnection().prepareStatement(querysql);
           statement.setString(1, name);
           statement.setString(2, Password);
           statement.setString(3, telepon);
           statement.setString(4, Email);
           statement.setString(5, tempattinggal);
           if(Password.equals(konfir)){
               statement.executeUpdate();
           JOptionPane.showMessageDialog(this, "data berhasil ditambahkan","berhasil", JOptionPane.INFORMATION_MESSAGE);
           new menu().setVisible(true);
           this.dispose();
             if(name.isEmpty()||Email.isEmpty()||Password.isEmpty()||telepon.isEmpty()){
               JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong", "error", JOptionPane.ERROR_MESSAGE);
                } 
           }else {
                JOptionPane.showMessageDialog(this, "password-confirm tidak cocok", "error", JOptionPane.ERROR_MESSAGE);
           }
           
       }catch(Exception ex){
           System.out.println(ex.getMessage());
       }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
       if(view1.isSelected()){
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_view1ActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
          if(view2.isSelected()){
            konfirmasi.setEchoChar((char)0);
        }else{
            konfirmasi.setEchoChar('*');
        }
    }//GEN-LAST:event_view2ActionPerformed

    private void konfirmasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konfirmasiKeyReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_konfirmasiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupsite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupsite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField konfirmasi;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField telpon;
    private javax.swing.JCheckBox view1;
    private javax.swing.JCheckBox view2;
    // End of variables declaration//GEN-END:variables
}
