/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submenu;

import database.dbconnection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class menu4_returbarang extends javax.swing.JFrame {
  public void auto_id() {
     PreparedStatement statement;
        ResultSet result;
        try{
        String sql="select id_retur from retur order by id_retur desc limit 1";
        statement=dbconnection.getConnection().prepareStatement(sql);
        result=statement.executeQuery();
        if(result.next()){
            String no=result.getString("id_retur");
            int co=no.length();
            String txt=no.substring(0, 2);
            String num=no.substring(2,co);
            int n=Integer.parseInt(num);
            n++;
            String anum=Integer.toString(n);
            String ftxt=txt+anum;
            kode.setText(ftxt);
            
        }else{
            kode.setText("RT1");
        }
        }catch(HeadlessException | SQLException ex){
           System.out.println(ex.getMessage());
       }
}
   public void tampilan_namapelanggan(){
         PreparedStatement statement;
         ResultSet result;
    
        try{
    
            String sql="Select *From pembayaran";
           statement = dbconnection.getConnection().prepareStatement(sql);
            result=statement.executeQuery();
            while(result.next()){
               nama.addItem(result.getString("nama_pelanggan")); 
              
            }result.last();
            int jumlahdata=result.getRow();
            result.first();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    public void tampilan_namabarang(){
         PreparedStatement statement;
         ResultSet result;
    
        try{
    
            String sql="Select *From transaksi";
           statement = dbconnection.getConnection().prepareStatement(sql);
            result=statement.executeQuery();
            while(result.next()){
               namabarang.addItem(result.getString("nama_barang")); 
              
            }result.last();
            int jumlahdata=result.getRow();
            result.first();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
     public void insert_retur(){
       
          PreparedStatement statement; 
          String masukkode= kode.getText();
          String namauser=String.valueOf(nama.getSelectedItem());
          String namabar=String.valueOf(namabarang.getSelectedItem());
          String jenisrusak=String.valueOf(jeniskerusakan.getSelectedItem());
            int jumlah1= Integer.parseInt(jumlahbarang.getText());
          String jumlahbeli=Integer.toString(jumlah1);
          
          String querysql="INSERT INTO retur (id_retur,nama_pelanggan,nama_barang,jumlah, jenis_kerusakan) VALUES(?,?,?,?,?)";
          
       try{
           statement = dbconnection.getConnection().prepareStatement(querysql);
           statement.setString(1, masukkode);
           statement.setString(2, namauser);
           statement.setString(3, namabar);
           statement.setString(4, jumlahbeli);
           statement.setString(5, jenisrusak);
          
           if(!namauser.isEmpty()){
               statement.executeUpdate();
             // jumlah_transaksi(namauser, date, masukkode);
              JOptionPane.showMessageDialog(this, "data berhasil ditambahkan","berhasil", JOptionPane.INFORMATION_MESSAGE);
            
            //  tampilan_transaksi();
             if(namauser.isEmpty()){
               JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong", "error", JOptionPane.ERROR_MESSAGE);
                } 
           }else {
                JOptionPane.showMessageDialog(this, "password-confirm tidak cocok", "error", JOptionPane.ERROR_MESSAGE);
           }
           
       }catch(HeadlessException | SQLException ex){
           System.out.println(ex.getMessage());
       }
    }
    /**
     * Creates new form menu4_returbarang
     */
    public menu4_returbarang() {
        initComponents();
        tampilan_namapelanggan();
        tampilan_namabarang();
        auto_id();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskerusakan = new javax.swing.JComboBox<>();
        jumlahbarang = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        submit = new javax.swing.JLabel();
        namabarang = new javax.swing.JComboBox<>();
        nama = new javax.swing.JComboBox<>();
        search = new javax.swing.JLabel();
        search2 = new javax.swing.JLabel();
        search1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jeniskerusakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "warna luntur", "robek", "jahitan lepas", "kurang kancing", "dan lainnya" }));
        getContentPane().add(jeniskerusakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 280, 30));

        jumlahbarang.setBorder(null);
        jumlahbarang.setOpaque(false);
        getContentPane().add(jumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 280, 30));
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 280, 30));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 110, 50));

        getContentPane().add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 280, 30));

        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 280, 30));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, 30));
        getContentPane().add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 30));
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/menu4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        insert_retur();
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu4_returbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu4_returbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu4_returbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu4_returbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu4_returbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jeniskerusakan;
    private javax.swing.JTextField jumlahbarang;
    private javax.swing.JTextField kode;
    private javax.swing.JComboBox<String> nama;
    private javax.swing.JComboBox<String> namabarang;
    private javax.swing.JLabel search;
    private javax.swing.JLabel search1;
    private javax.swing.JLabel search2;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
}
